services:
  proxy:
    build: /home/derek/Docker/Dockerfiles/proxy
    container_name: proxy
    restart: always
    network_mode: host
    volumes:
      - /home/derek/Docker/Volumes/proxy/config.json:/app/config.json
      - /home/derek/Docker/Volumes/proxy/servers.json:/app/servers.json
  octoprint:
    build: /home/derek/Docker/Dockerfiles/octoprint
    container_name: octoprint
    restart: always
    ports:
      - 5000:80
    volumes:
      - /home/derek/Docker/Volumes/octoprint:/octoprint
      - /dev:/dev
    privileged: true
  derek-cam:
    build: /home/derek/Docker/Dockerfiles/derek-cam
    container_name: derek-cam
    restart: always
    ports:
      - 5001:5001
    volumes:
      - /dev:/dev
      - /home/derek/Docker/Volumes/derek-cam/config.json:/app/config.json
      - /home/derek/Docker/Volumes/derek-cam/script.js:/app/script.js 
      - /home/derek/Docker/Volumes/derek-cam/offline.jpg:/app/offline.jpg
      - /home/derek/Docker/Volumes/derek-cam/error.jpg:/app/error.jpg
    privileged: true
  derek-psu:
    build: /home/derek/Docker/Dockerfiles/derek-psu
    container_name: derek-psu
    restart: always
    ports:
      - 5002:5002
      - 9999:9999
    volumes:
      - /home/derek/Docker/Volumes/derek-psu/config.json:/app/config.json