version: "3.8"
services:
  octoprint:
    image: octoprint/octoprint
    container_name: octoprint
    restart: always
    ports:
      - 5000:80
    volumes:
      - /home/derek/Docker/octoprint:/octoprint
      - /dev/ttyUSB0:/dev/ttyUSB0
    privileged: true